apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homelab-route-public
  namespace: default
spec:
  parentRefs:
    - name: homelab-gateway
      namespace: envoy-gateway-system
      sectionName: https-root
  hostnames:
    - seaze.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: anubis
          namespace: anubis
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homelab-route-public-legacy
  namespace: default
spec:
  parentRefs:
    - name: homelab-gateway
      namespace: envoy-gateway-system
  hostnames:
    - homelab-matt.centralus.cloudapp.azure.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: anubis
          namespace: anubis
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homelab-route-authentik
  namespace: default
spec:
  parentRefs:
    - name: homelab-gateway
      namespace: envoy-gateway-system
      sectionName: https-auth
  hostnames:
    - auth.seaze.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Forwarded-Proto
                value: https
              - name: X-Forwarded-Host
                value: auth.seaze.dev
      backendRefs:
        - name: authentik-server
          namespace: authentik
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homelab-route-outpost
  namespace: default
spec:
  parentRefs:
    - name: homelab-gateway
      namespace: envoy-gateway-system
      sectionName: https-root
  hostnames:
    - seaze.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /outpost.goauthentik.io
      backendRefs:
        - name: authentik-server
          namespace: authentik
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homelab-route-protected
  namespace: default
spec:
  parentRefs:
    - name: homelab-gateway
      namespace: envoy-gateway-system
      sectionName: https-root
  hostnames:
    - seaze.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /dashboard
      backendRefs:
        - name: homepage
          namespace: homepage
          port: 80
